language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - cd python
# command to run tests
script: py.test proxcard_auth.py
